title:            Max's Corner
description:      A website for the things that I, maxpowa, am currently working on!
disqus_shortname: 
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://maxpowa.github.io

# Owner/author information
owner:
  name:           Max Gurela
  avatar:         avatar.png
  bio:            "I like to make minecraft mods in my free time! Currently schooling in C#."
  email:          maxpowa1@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        maxpowa_
  github:         maxpowa
  # Minecraft forum user ID, pulled from the url http://www.minecraftforum.net/user/500540-maxpowa/
  minecraftforum: 500540
  devbukkit:      maxpowa
  modsio:         maxpowa

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-38742513-2

# Links to include in top navigation
# For external links add external: true
links:
  - title: Unknowncraft
    url: http://unknowncraftnetwork.enjin.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Edmonton
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
